# Generated by Django 4.2.6 on 2023-11-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereToEat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
