# Generated by Django 3.2.22 on 2023-10-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereToEat', '0002_auto_20231018_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'custom_table_name',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
